![Los Angeles skyline](la_skyline.jpg)

Los Angeles, California 😎. The City of Angels. Tinseltown. The Entertainment Capital of the World! 

Known for its warm weather, palm trees, sprawling coastline, and Hollywood, along with producing some of the most iconic films and songs. However, as with any highly populated city, it isn't always glamorous and there can be a large volume of crime. That's where you can help!

You have been asked to support the Los Angeles Police Department (LAPD) by analyzing crime data to identify patterns in criminal behavior. They plan to use your insights to allocate resources effectively to tackle various crimes in different areas.

## The Data

They have provided you with a single dataset to use. A summary and preview are provided below.

It is a modified version of the original data, which is publicly available from Los Angeles Open Data.

# crimes.csv

| Column     | Description              |
|------------|--------------------------|
| `'DR_NO'` | Division of Records Number: Official file number made up of a 2-digit year, area ID, and 5 digits. |
| `'Date Rptd'` | Date reported - MM/DD/YYYY. |
| `'DATE OCC'` | Date of occurrence - MM/DD/YYYY. |
| `'TIME OCC'` | In 24-hour military time. |
| `'AREA NAME'` | The 21 Geographic Areas or Patrol Divisions are also given a name designation that references a landmark or the surrounding community that it is responsible for. For example, the 77th Street Division is located at the intersection of South Broadway and 77th Street, serving neighborhoods in South Los Angeles. |
| `'Crm Cd Desc'` | Indicates the crime committed. |
| `'Vict Age'` | Victim's age in years. |
| `'Vict Sex'` | Victim's sex: `F`: Female, `M`: Male, `X`: Unknown. |
| `'Vict Descent'` | Victim's descent:<ul><li>`A` - Other Asian</li><li>`B` - Black</li><li>`C` - Chinese</li><li>`D` - Cambodian</li><li>`F` - Filipino</li><li>`G` - Guamanian</li><li>`H` - Hispanic/Latin/Mexican</li><li>`I` - American Indian/Alaskan Native</li><li>`J` - Japanese</li><li>`K` - Korean</li><li>`L` - Laotian</li><li>`O` - Other</li><li>`P` - Pacific Islander</li><li>`S` - Samoan</li><li>`U` - Hawaiian</li><li>`V` - Vietnamese</li><li>`W` - White</li><li>`X` - Unknown</li><li>`Z` - Asian Indian</li> |
| `'Weapon Desc'` | Description of the weapon used (if applicable). |
| `'Status Desc'` | Crime status. |
| `'LOCATION'` | Street address of the crime. |

In [37]:
# Re-run this cell
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
crimes = pd.read_csv("crimes.csv", dtype={"TIME OCC": str})
crimes.head()

       DR_NO   Date Rptd  ...  Status Desc                                 LOCATION
0  220314085  2022-07-22  ...  Invest Cont  2500 S  SYCAMORE                     AV
1  222013040  2022-08-06  ...  Invest Cont  3300    SAN MARINO                   ST
2  220614831  2022-08-18  ...  Invest Cont                        1900    TRANSIENT
3  231207725  2023-02-27  ...  Invest Cont  6200    4TH                          AV
4  220213256  2022-07-14  ...  Invest Cont  1200 W  7TH                          ST

[5 rows x 12 columns]

In [38]:
crimes.dtypes

DR_NO            int64
Date Rptd       object
DATE OCC        object
TIME OCC        object
AREA NAME       object
Crm Cd Desc     object
Vict Age         int64
Vict Sex        object
Vict Descent    object
Weapon Desc     object
Status Desc     object
LOCATION        object
dtype: object

In [39]:
# Start coding here
# Use as many cells as you need
crimes['TIME OCC'] = crimes['TIME OCC'].str[0:2]
crimes.head()

       DR_NO   Date Rptd  ...  Status Desc                                 LOCATION
0  220314085  2022-07-22  ...  Invest Cont  2500 S  SYCAMORE                     AV
1  222013040  2022-08-06  ...  Invest Cont  3300    SAN MARINO                   ST
2  220614831  2022-08-18  ...  Invest Cont                        1900    TRANSIENT
3  231207725  2023-02-27  ...  Invest Cont  6200    4TH                          AV
4  220213256  2022-07-14  ...  Invest Cont  1200 W  7TH                          ST

[5 rows x 12 columns]

In [40]:
crimes['TIME OCC'] = crimes['TIME OCC'].astype('int')

In [41]:
crime_hours = crimes.groupby('TIME OCC').size().sort_values(ascending = False)
crime_hours.name = 'Crime Count'
crime_hours.head()

TIME OCC
12    13663
18    10125
17     9964
20     9579
15     9393
Name: Crime Count, dtype: int64

In [42]:
peak_crime_hour = crime_hours.index[0]
peak_crime_hour

12

In [43]:
night_crimes = crimes[crimes['TIME OCC'].isin([22, 23, 00, 1, 2, 3])]
night_crimes.head()

        DR_NO  ...                                  LOCATION
8   231207476  ...   8800    HAAS                         AV
10  221711184  ...   8300    WHITE OAK                    AV
30  221314362  ...   1600 E  OLYMPIC                      BL
33  231307252  ...                          6600 S  BROADWAY
36  221614254  ...  10200    TELFAIR                      AV

[5 rows x 12 columns]

In [44]:
night_crime_area_count = night_crimes.groupby('AREA NAME').size().sort_values(ascending= False)
night_crime_area_count.name = 'Crime Count'
night_crime_area_count.head()

AREA NAME
Central        3312
Hollywood      2699
77th Street    2558
Southwest      2347
Southeast      2218
Name: Crime Count, dtype: int64

In [45]:
peak_night_crime_location = night_crime_area_count.index[0]
peak_night_crime_location

'Central'

In [46]:
crimes.head()

       DR_NO   Date Rptd  ...  Status Desc                                 LOCATION
0  220314085  2022-07-22  ...  Invest Cont  2500 S  SYCAMORE                     AV
1  222013040  2022-08-06  ...  Invest Cont  3300    SAN MARINO                   ST
2  220614831  2022-08-18  ...  Invest Cont                        1900    TRANSIENT
3  231207725  2023-02-27  ...  Invest Cont  6200    4TH                          AV
4  220213256  2022-07-14  ...  Invest Cont  1200 W  7TH                          ST

[5 rows x 12 columns]

In [47]:
import numpy as np
conditions = [
    crimes['Vict Age'] <= 17,
    (crimes['Vict Age'] > 17) & (crimes['Vict Age'] <= 25),
    (crimes['Vict Age'] > 25) & (crimes['Vict Age'] <= 34),
    (crimes['Vict Age'] > 34) & (crimes['Vict Age'] <= 44),
    (crimes['Vict Age'] > 44) & (crimes['Vict Age'] <= 54),
    (crimes['Vict Age'] > 54) & (crimes['Vict Age'] <= 64),
    crimes['Vict Age'] > 64
]

choices = ['0-17', '18-25','26-34', '35-44', '45-54', '55-64', '65+']

crimes['Age Group'] = np.select(conditions, choices, default= 'Unknown')
crimes.head()

       DR_NO   Date Rptd  ...                                 LOCATION  Age Group
0  220314085  2022-07-22  ...  2500 S  SYCAMORE                     AV      26-34
1  222013040  2022-08-06  ...  3300    SAN MARINO                   ST      55-64
2  220614831  2022-08-18  ...                        1900    TRANSIENT      26-34
3  231207725  2023-02-27  ...  6200    4TH                          AV      35-44
4  220213256  2022-07-14  ...  1200 W  7TH                          ST        65+

[5 rows x 13 columns]

In [48]:
victim_ages = crimes.groupby('Age Group').size().sort_values(ascending= False)
victim_ages.name = 'Crime Frequency'
victim_ages

Age Group
26-34    47470
35-44    42157
45-54    28353
18-25    28291
55-64    20169
65+      14747
0-17      4528
Name: Crime Frequency, dtype: int64